# -*- coding: utf-8 -*-
"""「Data Types.ipynb」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sT6PG6CIpn5Er7shBboU4jzqKXFLN_iv

### **Data Types Introduction**

- **What are Data Types?**
    - In computer science, a data type is a classification that specifies which type of value a variable can hold. Think of it as a label for the kind of data (e.g., numbers, texts, true/false values) we're dealing with.
    - For instance, if we label something as a 'text' type, it means the variable will hold textual information like names, addresses, etc.

#### **Why Do We Need Different Data Types?**
1. **Efficiency:** Different data types use different amounts of memory. By choosing the right data type, we ensure our programs run efficiently.
2. **Precision:** Some tasks require precision. For instance, financial calculations might need decimal values instead of whole numbers.
3. **Clarity:** Using the right data type makes the code more readable and understandable.
4. **Error Prevention:** Certain operations are only valid for specific data types. Having the right type can prevent errors. For example, you wouldn't want to accidentally add someone's name to their age.

---

### **Integers and Floats**

#### **Definition and Examples of Integers and Floats**
- **Integers:**
    - These are whole numbers that can be positive, negative, or zero. They do not have decimal points.
    - Examples: -3, -2, -1, 0, 1, 2, 3, ...
- **Floats:**
    - Also known as floating-point numbers, these are numbers that have a decimal point.
    - They can represent real numbers (both rational and irrational numbers).
    - Examples: -3.5, 0.0, 2.71, 3.14, ...

#### **The Difference Between the Two**
1. **Representation:** Integers are whole numbers without a decimal point, while floats have a decimal point.
2. **Memory:** Floats typically require more memory than integers due to the precision they carry.
3. **Operations:** Some operations might yield different results. For instance, dividing two integers might truncate the result, whereas dividing two floats will retain the decimal portion.

#### **Practice: Create Variables of Integer and Float Types and Perform Basic Arithmetic Operations**
1. **Creating Variables:**
```python
int_variable = 5
float_variable = 5.5
```
2. **Arithmetic Operations:**
    - **Addition:** `int_variable + 3` will result in `8`, but `float_variable + 3` will result in `8.5`.
    - **Division:** `int_variable / 2` might differ in some languages in its result compared to `float_variable / 2`. In Python 3, both will return a float, but in some languages, integer division truncates the result.
    - **Multiplication:** `int_variable * 2` will result in `10`, and `float_variable * 2` will result in `11.0`.

3. **Experimentation:** Create your own integer and float variables and experiment with various arithmetic operations to observe the outcomes.

---
"""

#Experiment with integers and floats in this cell

"""**1. Coffee Shop Calculator**
   
**Objective:** Calculate the total cost of items ordered at a coffee shop.

- **Instructions:**
   - Imagine you're visiting your favorite coffee shop.
   - Use the `input()` function to ask the user to specify the number of espressos, lattes, and muffins they'd like to "buy". Convert these to integer values.
   - Similarly, take user input for the prices of each item and convert these to float values.
   - Write a program to calculate and display the total cost.

---
"""

#Your code for exercise 1 in here
print("number of espressos")
espresso=int(input())
print("number of lattes")
latte=int(input())
print("number of muffins")
muffin=int(input())
print("price:", espresso*3+latte*2+muffin*1)

"""**2. Rocket Launch Countdown**
   
**Objective:** Simulate a rocket launch countdown.

- **Instructions:**
   - Use the `input()` function to ask the user for a starting countdown number and convert it to an integer.
   - Write a loop that subtracts 1 from the variable and prints the current countdown number each iteration.
   - Add a delay (using time.sleep in Python) of 0.5 seconds between each countdown number.

---

"""

#Your code for exercise 2 in here
import time;
l=int(input())

while l>0:
  l = l-1
  print(l)
  time.sleep(1)

"""**3. Your Weight on Other Planets**
   
**Objective:** Find out how much you'd weigh on different planets based on their gravity.

- **Instructions:**
   - Use the `input()` function to ask the user for their weight on Earth and convert this to a float.
   - Create float variables for the gravity factor of different planets (e.g., Mars is about 0.38 of Earth's gravity).
   - Calculate and display how much they'd weigh on each of these planets.

---
"""

#Exercise 3
earth_weight=float(input("ur weight on earth:"))
mars=0.38
print("ur weight on mars:", earth_weight*mars)

"""**4. Pizza Party Calculator**
   
**Objective:** Calculate the cost per slice of pizza.

- **Instructions:**
   - Use the `input()` function to ask the user how many pizzas they bought and the total cost. Convert these values appropriately (integer for number of pizzas, float for cost).
   - Ask the user to specify how many slices each pizza has and convert this to an integer.
   - Calculate and display the cost per slice.

---
"""

#Exercise 4
no_of_pizzas=int(input("number of pizzas u r buying:"))
cost_of_pizzas=float(input("cost of the pizzas:"))
slices=int(input("number of slices:"))
print("cost per slice:", (cost_of_pizzas/no_of_pizzas)/slices)

"""
**5. Travel Budget Calculator**
   
**Objective:** Calculate the total budget required for a trip.

- **Instructions:**
   - Imagine you're planning a trip to your dream destination.
   - Use the `input()` function to ask the user for the number of days they plan to stay and convert this to an integer.
   - Ask the user to specify the estimated daily expenses for food, accommodation, and sightseeing. Convert these to float values.
   - Write a program to calculate and display the total estimated cost for the trip.

---"""

#Exercise 5
no_of_days=int(input("number of days:"))
cost=float(input("$ u spend on the trip per day:"))
print("total cost:", no_of_days*cost)